# Generated by Django 4.2.4 on 2023-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uploadedpdf_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
