# Generated by Django 4.2.5 on 2023-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_openaimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_size', models.PositiveIntegerField(default=600)),
                ('chunk_overlap', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
