name: Build and deploy Python app to Azure Web App - unitechchat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  build-deploy:
    runs-on: ubuntu-latest
    needs: azure-login
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect Static Files
        run: python manage.py collectstatic --noinput

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unitechchat'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_95B18C1B78494E04B47EB188542B3FE4 }}
